name: Re-tag images and Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  re-tag:
    name: Re-tag image
    runs-on: default
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Re-tag image application image
        uses: cloudbeds/composite-actions/docker/crane-re-tag/aws-ecr@v2
        with:
          # image_name: Only registry path is required. AWS ECR registry address will be automatically set by composite-actions
          image_name: ${{ github.event.repository.name }}
          src_tag: ${{ github.sha }}
          dst_tag: ${{ github.ref_name }}
